services:
  pwscraper:
    build: .
    ports:
      - 8080:8080
  nginx:
    image: nginx@sha256:6e23479198b998e5e25921dff8455837c7636a67111a04a635cf1bb363d199dc
    ports:
      - 6080:80
    volumes:
      - ./src/test/resources/nginx/www:/usr/share/nginx/html
      - ./src/test/resources/nginx/nginx.conf:/etc/nginx/conf.d/default.conf