services:
  pwscraper:
    build: .
    ports:
      - 8080:8080
  nginx:
    image: nginx@sha256:d0913a153ae2aefba815166d75587667a05773843d8f1726024100cd73462a09
    ports:
      - 6080:80
    volumes:
      - ./src/test/resources/nginx/www:/usr/share/nginx/html
      - ./src/test/resources/nginx/nginx.conf:/etc/nginx/conf.d/default.conf